//
//  NotificationViewController.swift
//  MyContentExtension
//
//  Created by Andrew Huber on 3/21/17.
//  Copyright © 2017 Andrew Huber. All rights reserved.
//

import UIKit
import UserNotifications
import UserNotificationsUI

class NotificationViewController: UIViewController, UNNotificationContentExtension {
    
    // =====================================================================================================
    // In order to witness the behavior of these functions with the debugger and to see the output 
    // generated by print statements should they be inserted into these functions, one must run this
    // app with "MyContentExtension" as the target. 
    // =====================================================================================================

    @IBOutlet weak var imageView: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any required interface initialization here.
    }
    
    func didReceive(_ notification: UNNotification) {
        guard let attachment = notification.request.content.attachments.first else {
            return
        }
        
        if attachment.url.startAccessingSecurityScopedResource() {
            let imageData = try? Data(contentsOf: attachment.url)
            if let img = imageData {
                imageView.image = UIImage(data: img)
            }
        }
    }
    
    func didReceive(_ response: UNNotificationResponse, completionHandler completion: @escaping (UNNotificationContentExtensionResponseOption) -> Void) {
        
        if response.actionIdentifier == "fistBump" {
            completion(.dismissAndForwardAction)
        }
        else if response.actionIdentifier == "dismiss" {
            completion(.dismiss)
        }
    }

}
